#pragma once

#define MANUFACTURER "Ufasoft"

#define MANUFACTURER_DOMAIN "ufasoft.com"

#define MANUFACTURER_HTTP_URL "http://" MANUFACTURER_DOMAIN
#define MANUFACTURER_NEWS_URL MANUFACTURER_HTTP_URL "/forum/"
#define MANUFACTURER_FTP_URL "ftp://ftp." MANUFACTURER_DOMAIN
#define MANUFACTURER_EMAIL "support@" MANUFACTURER_DOMAIN
#define MANUFACTURER_FAX ""
#define MANUFACTURER_REGISTER_URL MANUFACTURER_HTTP_URL "/register/"
#define MANUFACTURER_NOTIFY_URL MANUFACTURER_HTTP_URL "/cgi-bin/notify.cgi"
#define MANUFACTURER_BUGREPORT MANUFACTURER_HTTP_URL "/trac/newticket"
#define MANUFACTURER_CRASHDUMP_URL MANUFACTURER_HTTP_URL "/cgi-bin/crashdump.cgi"
#define INTERNETSITE _T("E-Mail: ") MANUFACTURER_EMAIL ", " MANUFACTURER_HTTP_URL
#define MANUFACTURER_RESERVED_URL "http://sockschain.com"

#define MANUFACTURER_ACTIVATE_URL MANUFACTURER_HTTP_URL "/cgi-bin/activate.cgi"
#define MANUFACTURER_RESERVED_ACTIVATE_URL  "http://xi.ufasoft.com:81/cgi-bin/activate.cgi"
