#define VER_PRODUCTVERSION_MAJOR 1
#define VER_PRODUCTVERSION_MINOR 19
#define VER_PRODUCTVERSION_BUILD 9

#ifndef VER_PRODUCTNAME_STR
#	define VER_PRODUCTNAME_STR "Coin"
#endif

#ifndef VER_EXT_URL
#	define VER_EXT_URL "http://ufasoft.com/coin"
#endif

#define VER_LEGALCOPYRIGHT_YEARS "2011-2019"
