#define _USRDLL

#define VER_FILEDESCRIPTION_STR "DBLite"
#define VER_INTERNALNAME_STR "dblite"
#define VER_ORIGINALFILENAME_STR "dblite.dll"
#define VER_PRODUCTVERSION 4,1,0,0
#define VER_PRODUCTVERSION_STR "4.1"

