#pragma once

#define UCFG_MANUFACTURER "Ufasoft"

#define UCFG_MANUFACTURER_DOMAIN 		"ufasoft.com"
#define UCFG_MANUFACTURER_HTTP_URL 		"https://" UCFG_MANUFACTURER_DOMAIN
#define UCFG_MANUFACTURER_NEWS_URL 		UCFG_MANUFACTURER_HTTP_URL "/forum/"
#define UCFG_MANUFACTURER_EMAIL 		"support@" UCFG_MANUFACTURER_DOMAIN
#define UCFG_MANUFACTURER_REGISTER_URL 	UCFG_MANUFACTURER_HTTP_URL "/register/"
#define UCFG_MANUFACTURER_NOTIFY_URL 	UCFG_MANUFACTURER_HTTP_URL "/cgi-bin/notify.cgi"
#define UCFG_MANUFACTURER_BUGREPORT 	UCFG_MANUFACTURER_HTTP_URL "/trac/newticket"
#define UCFG_MANUFACTURER_CRASHDUMP_URL UCFG_MANUFACTURER_HTTP_URL "/cgi-bin/crashdump.cgi"
#define UCFG_INTERNETSITE _T("E-Mail: ") 	UCFG_MANUFACTURER_EMAIL ", " UCFG_MANUFACTURER_HTTP_URL
#define UCFG_MANUFACTURER_RESERVED_URL 	"http://sockschain.com"

#define UCFG_MANUFACTURER_ACTIVATE_URL 	UCFG_MANUFACTURER_HTTP_URL "/cgi-bin/activate.cgi"
